image: node:14

pipelines:
  branches:
    release:
      - step:
          name: deploy
          caches:
            - node
          script:
            - ./build/scripts/build.sh
            - ./build/scripts/build_image.sh
