image: node:16

pipelines:
  branches:
    release:
      - step:
          name: deploy
          caches:
            - node
            - docker
          services:
            - docker
          script:
            - yarn
            - yarn build
            - ./build/scripts/build_image.sh
